# Generated by Django 4.0.1 on 2022-02-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категории товаров',
                'verbose_name_plural': 'Категория товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media/', verbose_name='Фотография продукта')),
                ('namespace', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('star', models.IntegerField(verbose_name='Количество звезд')),
                ('price', models.IntegerField(verbose_name='Цена за товар')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('sku', models.IntegerField(default=983649, verbose_name='Код товара')),
                ('gender', models.IntegerField(choices=[(1, 'Для Мальчиков'), (2, 'Для Девочек'), (3, 'Для Малышей')], verbose_name='Принадлежность товара')),
                ('category', models.ManyToManyField(to='indexing.Categories')),
            ],
            options={
                'verbose_name': 'Товары сайта',
                'verbose_name_plural': 'Товар сайта',
            },
        ),
    ]
