# Generated by Django 4.0.2 on 2022-02-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Политику конфиденциальности можно и нужно добавлять один раз!', verbose_name='Содержание политики конфиденциальности')),
            ],
            options={
                'verbose_name': 'Политика',
                'verbose_name_plural': 'Политика',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media/', verbose_name='Фотография')),
                ('author', models.CharField(default='Администратор', max_length=100, verbose_name='Опубликовано')),
                ('date', models.DateTimeField(verbose_name='время публикации')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Акции',
                'verbose_name_plural': 'Акция',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Содержимое поля можно и нужно добавлять один раз!', verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Оплата и доставка',
                'verbose_name_plural': 'Оплата и доставка',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='trand',
            field=models.BooleanField(default=True, verbose_name='Трендовый товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.IntegerField(default=288548, verbose_name='Код товара'),
        ),
    ]
